### ISSUE TITLE
"Maximum call stack size exceeded" when using as dependency in addon

### ISSUE THREAD

**Issue by jacobq** [brianhjelle/ember-plotly-shim#1]
Steps to reproduce: (also currently [here](https://github.com/jacobq/junk-addon))

* `ember addon junk-addon`
* `cd junk-addon`
* `ember install ember-plotly-shim`
* Edit `package.json` & move `ember-plotly-shim`  from `devDependencies` to `dependencies`
  (or run `npm uninstall --save-dev ember-plotly-shim; npm install --save ember-plotly-shim;`
* `npm install` or `yarn`
* `ember build` --> dies with "Maximum call stack size exceeded" (while `⠋ Building`)

```
$ ember v
ember-cli: 3.1.0-beta.1
node: 8.9.4
os: linux x64
```

**Comment by jacobq** [comment]
By stuffing a debugger statement at a line from the stack trace and [running with](medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27) 
`node --inspect-brk ./node_modules/.bin/ember build` I found the infinite loop here:
![image](https://user-images.githubusercontent.com/1633459/37174178-6e64ef14-22db-11e8-91ec-541249bc227a.png)

**Comment by jacobq** [comment]
I don't think this addon's `included` function [should be calling `this._super...`](https://github.com/brianhjelle/ember-plotly-shim/blob/master/index.js#L13). The ember-cli [example of `included` does not do this](https://ember-cli.com/api/classes/Addon.html#method_included).

**Comment by dfreeman** [comment]
It should _definitely_ be calling super—failing to call super is the source of a lot of bugs in addons in the wild. The problem here is that the first argument to `apply` should be `this`, not `app`
