### ISSUE TITLE
Version number in package.json is out of sync

### ISSUE THREAD

**Issue by jacobq** [brianhjelle/ember-plotly-shim#7]
Although it's at least correct [in `npm`](https://www.npmjs.com/package/ember-plotly-shim), it looks like the [`version` property is out of date in `package.json`](https://github.com/brianhjelle/ember-plotly-shim/blob/0a4ef72e0016528d1cdc20144c37c5f5598d06cd/package.json#L3)

**Comment by brianhjelle** [comment]
Thanks for catching this.  It is resolved now.
