### ISSUE TITLE
Document alternative solution?

### ISSUE THREAD

**Issue by jacobq** [brianhjelle/ember-plotly-shim#8]
It seems that [`ember-auto-import`](https://github.com/ef4/ember-auto-import) now offers a more general solution for (ES) `import`ing modules from npm. Are there advantages to using this shim instead? (I'm not quite sure how bundles weigh into things, etc.)

**Comment by brianhjelle** [comment]
Great question.  I'm also not sure how ember-auto-import would work with the concept of bundles in plotly.  I'll try do some experimenting soon and see if I can't get plotly working with ember-auto-import.  If it does work, then it would eliminate the need for this addon.

**Comment by brianhjelle** [comment]
Looks like ember-auto-import isn't working on Windows machines right now.
https://github.com/ef4/ember-auto-import/issues/38

I tried it on Linux and I was able to get the pre-packaged bundles to work with a line like the one below for the basic bundle
`import Plotly from 'plotly.js/dist/plotly-basic.min.js';`

Once ember-auto-import works on Windows, I think we can deprecate this addon and document how to use it with plotly in the README.

**Comment by brianhjelle** [comment]
Looks like ember-auto-import works on Windows now.  I've updated the README to indicate that this addon is deprecated since using ember-auto-import is a nicer solution.
